name: gene_filtering
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r=4.0
  - r-base=4.0.3
  - r-ape
  - r-distory
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-glue
  - r-patchwork
  - r-phangorn
  - r-phytools
  - r-phylotools
  - r-seqinr
  - bioconductor-ggtree
  